inputs:
  - name: netbox
    config:
      server: netbox.nvidia.com
      token:  'aca55c22125454d787c1cc822037097d10cc61cc'
      ttl: 1h
      broker:
        - sc-it-mq-prd-01.nvidia.com:9092
        - sc-it-mq-prd-02.nvidia.com:9092
        - sc-it-mq-prd-03.nvidia.com:9092
  - name: vcenter
    config:
      defaults: &defaults
        username: user
        password: pass
        insecure: true
      
      ttl: 1h

      servers:
        - name: vcentersc02
          url: 127.0.0.1:8989 #vcentersc02.nvidia.com
          <<: *defaults